### ISSUE TITLE
ERROR: mapping values are not allowed here

### ISSUE THREAD

**Issue by GeekItTillItMhz** [mdhiggins/sonarr-sma#13]
_For starters thank you for the images and the mp4_automation script._

I received the below error when trying to run the docker-compose script on Debian 10 (Buster) with docker-compose version 1.21.0

> ERROR: yaml.scanner.ScannerError: mapping values are not allowed here
>   in "./docker-compose.yml", line 2, column 9

My docker-compose.yml file looked like:
```
yaml
  sonarr:
    image: mdhiggins/sonarr-sma:build
    container_name: sonarr
    volumes:
      - /opt/appdata/sonarr:/config
      - /opt/appdata/sma:/usr/local/sma/config
      - /home/username/media/tv:/tv
      - /home/username/downloads:/downloads
    ports:
      - 8989:8989
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
```
I was able to start the container successfully with the below:
```
version: "2.1"
services:
  sonarr:
    image: mdhiggins/sonarr-sma:build
    container_name: sonarr
    volumes:
      - /opt/appdata/sonarr:/config
      - /opt/appdata/sma:/usr/local/sma/config
      - /home/username/media/tv:/tv
      - /home/username/downloads:/downloads
    ports:
      - 8989:8989
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
```
This applies to your radarr-sma docker image as well.
