### ISSUE TITLE
NVENC still possible?

### ISSUE THREAD

**Issue by wdckwrth** [mdhiggins/sonarr-sma#56]
I had it working and then fat-fingered myself to an updated version. Now I think I am stuck since everything is rebased to Alpine. 

I have seen the readme and threads about using the linuxserver/ffmpeg image. It seems as easy as adding `runtime: nvidia` but I don't end up with an ffmpeg with h264_nvenc support. 

Can I still do something like this?

```
services:
  sonarr:
    container_name: sonarr-sma
    build:
      context: https://github.com/mdhiggins/sonarr-sma.git#build
      args:
        ffmpeg_tag: 5.1-nvidia2004
        sonarr_tag: 3.0.10
    [snip]
    environment:
      - SMA_HWACCEL=true
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - LD_LIBRARY_PATH=/usr/local/cuda-11.4/lib64
    runtime: nvidia    

```
