### ISSUE TITLE
No VA display found for device error until container restarted

### ISSUE THREAD

**Issue by mtrolley** [mdhiggins/sonarr-sma#63]
I doubt this is a problem with this container, but recently I've been getting this error:

```
[AVHWDeviceContext @ 0x7ff3182f4e00] No VA display found for device /dev/dri/renderD128.
Device creation failed: -22.
Failed to set value 'vaapi=sma:/dev/dri/renderD128' for option 'init_hw_device': Invalid argument
Error parsing global options: Invalid argument

2024-10-29 13:58:01 - SonarrPostProcess - ERROR - Processing returned False.
2024-10-29 13:58:01 - SonarrPostProcess - ERROR - Error processing file.
Traceback (most recent call last):
  File "/usr/local/sma/postSonarr.py", line 230, in <module>
    sys.exit(1)
SystemExit: 1
```

Let me know if more context is needed.

This happens when sonarr post-processing runs. What I've found is that simply restarting the container fixes the problem, in that I can run a shell in the container and run a manual conversion no problem. I didn't have this before, so I'm not sure what changed. I'm hoping someone else that uses this container may know.

**Comment by mdhiggins** [comment]
Nothing has changed in a while. This is an ffmpeg error from it not having access to your hardware device. Are the manual conversions your triggering actually using hardware encoding? Probably need to share your docker info too to make sure the hardware is actually passed correctly.

**Comment by mtrolley** [comment]
I realize I wasn't completely right when I said "nothing has changed" because what I _did_ change was switching from one monolithic `docker-compose.yaml` file into separate files for each container and having the main compose file `include` the others. The contents didn't change other than reformatting from what I remember though. Here's the docker compose for sonarr:

```
services:
  sonarr:
    container_name: sonarr
    devices:
      - /dev/dri:/dev/dri
    environment:
      PGID: "${PGID}"
      PUID: "${PUID}"
      SMA_HWACCEL: "true"
      SMA_USE_REPO: "true"
      TZ: "${TZ}"
    hostname: sonarr
    image: mdhiggins/sonarr-sma
    labels:
      - swag=enable
    ports:
      - 8989:8989
    restart: unless-stopped
    volumes:
      - type: bind
        source: ${VOLUME_CONFIG}/sonarr
        target: /config
        bind:
          create_host_path: true
      - type: bind
        source: ${VOLUME_CONFIG}/sonarr-sma
        target: /usr/local/sma/config
      - type: bind
        source: ${VOLUME_STORAGE}
        target: /storage
```

[Here's two logs](https://gist.github.com/mtrolley/daae832c4d45de7560aaf6187b4f000b). `failed.txt` is the log from the last file that failed when triggered by Sonarr postprocessing. `manual.txt` is the same file being processed manually and successfully after restarting the container. It's definitely uses hardware because I can check with `intel_gpu_top` and see it being used.
