### ISSUE TITLE
ffmpeg Error creating a MFX session: -9 on Alder Lake

### ISSUE THREAD

**Issue by xtrench** [mdhiggins/sonarr-sma#71]
So I'm getting "Error creating a MFX session: -9" when trying to use hardware acceleration with quicksync on an i3 12100
running apk add onevpl-intel-gpu --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing/ seems to fix it.

my docker compose
```
services:
  sonarr:
    image: ghcr.io/mdhiggins/sonarr-sma
    container_name: sonarr_sma
    volumes:
      - /var/lib/docker/volumes/sonarrsma_sonarr_config/_data:/config
      - /var/lib/docker/volumes/sonarrsma_sma_config/_data:/usr/local/sma/config
      - /mnt/Media4tb:/library2
      - /mnt/NVME0/Flash/Downloads:/downloads
      - /mnt/NVME0/Flash/Data:/data
    ports:
      - 8989:8989
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - SMA_HWACCEL=true
      - SMA_USE_REPO=true
      - SMA_UPDATE=true
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
```
